ALTER TYPE "AppTransactionType" RENAME VALUE 'FEE_PRO' TO 'FEE_SUBSCRIPTION';

ALTER TYPE "UserPlan" ADD VALUE 'DEVELOPER';

ALTER TABLE "ProSubscriptionPayment" ADD COLUMN "plan" "UserPlan" NOT NULL DEFAULT 'PRO';
